# Generated by Django 5.1.7 on 2025-04-19 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_event_newslettersubscriber_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('passkey', models.CharField(default='DEFAULT_PASSKEY', max_length=8)),
                ('role', models.CharField(default='Participant', max_length=50)),
                ('checked_in', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('missed', 'Missed'), ('success', 'Success')], default='registered', max_length=50)),
                ('checkin_link', models.CharField(blank=True, max_length=32, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('area_of_interest', models.CharField(default='General', max_length=100)),
                ('language', models.CharField(default='English', max_length=100)),
                ('communication', models.CharField(default='Email,Phone', max_length=100)),
                ('attended', models.BooleanField(default=False)),
                ('allow_marketing', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
