# Generated by Django 5.1.7 on 2025-04-19 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('area_of_interest', models.CharField(default='General', max_length=100)),
                ('subsector_of_interest', models.CharField(blank=True, max_length=100, null=True)),
                ('citizenship', models.CharField(max_length=100)),
                ('other_citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('email_verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('other_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('passkey', models.CharField(blank=True, max_length=6, null=True)),
                ('communication', models.CharField(default='Email,Phone', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
